### PR TITLE
Redirect the historical apps page to the current

### PR DESCRIPTION
**Pull request by orblivion**
1) This already happens on sandstorm.io. Perhaps by a server configuration. Putting it in the meta tag will make it more self-contained.
2) The blog links pointed to the old domain, sandstorm.io, and were furthermore using a "blog" subdomain that seems to be deprecated via a redirect, and furthermore that redirect was broken because it ends up with /news/news/ in the URL.

The one thing that sandstorm.io does right now is preserve stuff after ? and # in the URL. Not sure if we care about that, I think people will rarely ever land on this page.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
So I like the concept of keeping this site around somewhere. For an offline or corporate Sandstorm setup, this is probably the most implementable custom market example.

**Comment by orblivion** [comment]
Okay. So any old stray links on the Internet that point to sandstorm.io/apps would redirect appropriately as long as the old websites stays up. But it feels weird to keep links to sandstorm.io/apps around on our site. Maybe those should be edited to go directly to apps.sandstorm.io?

**Comment by orblivion** [comment]
But then again what if sandstorm.io redirects to sandstorm.org some day? Maybe the example custom corporate app market could be moved, and we redirect index like I do here?

**Comment by ocdtrekkie** [comment]
I mean nobody should ever inadvertently end up on sandstorm.org/apps since nowhere ever linked to it. I am also not too worried about things still referring to .io until those .io endpoints start to disappear.

**Comment by orblivion** [comment]
Since I'm about to start with the blog post and making references to sandstorm.org for images I felt like cleaning it up.

**Pull request closed without merging**
