### PR TITLE
Change header around

### PR DESCRIPTION
**Pull request by ocdtrekkie**
I'm deprioritizing "Get", "Technology", and "Features" which have links elsewhere on every page, and adding Donate up on the header. This also puts "News" first which I feel is important.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
@CaptainCalliope What do you think?

https://change-header.sandstorm-website-684.pages.dev/

**Comment by CaptainCalliope** [comment]
I looked through the commit history and I agree with every change you made. The only thing I noticed is that the words source and platform look like they're connected in my mobile view. It looks correct in landscape mode however.
Screenshot_20231015_000840_Chrome

**Comment by CaptainCalliope** [comment]
The Code navigation link needs to be updated, assuming the code base has been forked already.

**Comment by CaptainCalliope** [comment]
Great work!

**Comment by ocdtrekkie** [comment]
I spotted that mobile bug too, it's the same for sandstorm.io though we should fix it.

Have not forked the code, docs, apps, etc. yet. Probably won't until we have actual substantial changes. I intend to explain that a bit in our next blog post.

**Pull request merged**
