### PR TITLE
Desert Atlas blog post

### PR DESCRIPTION
**Pull request by orblivion**
- [x] Finish linked Github wiki page
- [x] [Release App](https://github.com/orblivion/desert-atlas/milestone/1)
- [x] Make sure the demo link works
- [x] Update the file name so that it shows up on the right date
    - [x] Update link back to blog post from Github wiki page accordingly

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
"I have listed some low hanging fruit at the end of this post" is no longer true.

**Comment by ocdtrekkie** [comment]
I would update the line I mentioned above to just be a link like the one near the end of the post, instead of asking them to look to the bottom and then get the link.

I would definitely prefer you use https://sandstorm.org/logos/app-demo-buttons/tryitnow-purp1.svg instead of adding your own modified version of it.

And then this is probably a bit of a nitpick, but I personally would run your images through something like tinypng.com. It converted your 173 KB image to a 49 KB image that looks indistinguishable. (The big difference TinyPNG claims to make is converting 24-bit color to 8-bit indexed color.)

**Comment by ocdtrekkie** [comment]
Oh, and finally, you'll need to rename the file to whatever the actual posting date is, so it doesn't show up as posted November 14th.

**Comment by orblivion** [comment]
I got the svg from here: https://raw.githubusercontent.com/sandstorm-io/logos/master/app-demo-buttons/tryitnow_purp1.svg. I think you pointed me here. It's not the same image. I'm glad it's the wrong one, the font shows up small.

**Comment by orblivion** [comment]
You can notice a little dithering with the tiny images but it's okay.

**Comment by orblivion** [comment]
I think I covered your issues other than the date. I added that to the checklist in the PR description.

**Review by ocdtrekkie — APPROVED** [review]

**Comment by orblivion** [comment]
How do you feel about the vertical margins on that button svg? I think it would look better to remove them. I think I can do it in Inkscape. I don't see this image being used anywhere else on this site, not sure if it's linked from somewhere on the Internet. So maybe I could just edit the file.

**Comment by ocdtrekkie** [comment]
I think you should just try switching to the PNG, which I don't think has the margins. Just change the extension.

**Comment by ocdtrekkie** [comment]
One of the things I learned removing the .io from the Sandcat was that every SVG app feels like formatting the file in it's own way, and uses it's own frame of reference. So even a minor tweak to the SVG is going to basically replace it entirely. I feel like that's too much effort for this, but I agree the margins are uncomfortably large in the blog post.

**Pull request merged**
